server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_db
    username: root
    password: AulaMatriz123
    driver: com.mysql.cj.jdbc.Driver
  application:
    name: ms-user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /aulamatriz-doc
  show-actuator: false
  packages-to-scan: com.ms.user.controller

control:
  exception:
    business: Business Exception
    system: System Exception